services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  postgres_api:
    image: postgres:15-alpine
    container_name: postgres_api_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: api_gateway_db
    ports:
      - '5432:5432'
    volumes:
      - api_db_data:/var/lib/postgresql/data
    restart: always

  postgres_user:
    image: postgres:15-alpine
    container_name: postgres_user_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: user_service_db
    ports:
      - '5433:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: always

  postgres_template:
    image: postgres:15-alpine
    container_name: postgres_template_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: template_service_db
    ports:
      - '5434:5432'
    volumes:
      - template_db_data:/var/lib/postgresql/data
    restart: always

  api-gateway-app:
    container_name: api_gateway_app
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway:/var/www/html
    environment:
      APP_NAME: 'Notification API Gateway'
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost:8000'
      DB_CONNECTION: pgsql
      DB_HOST: postgres_api
      DB_PORT: 5432
      DB_DATABASE: api_gateway_db
      DB_USERNAME: admin
      DB_PASSWORD: password123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      USER_SERVICE_URL: 'http://user-service:3000'
    depends_on:
      - postgres_api
      - rabbitmq
      - user-service

  api-gateway-nginx:
    container_name: api_gateway_nginx
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./api-gateway:/var/www/html
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway-app

  user-service:
    container_name: user_service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      PORT: 3000
      DATABASE_URL: 'postgresql://admin:password123@postgres_user:5432/user_service_db'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres_user
      - redis

  template-service:
    container_name: template_service
    build:
      context: ./template-service
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    environment:
      PORT: 3000
      DATABASE_URL: 'postgresql://admin:password123@postgres_template:5432/template_service_db'
    depends_on:
      - postgres_template

  email-push-service:
    container_name: email_push_service
    build:
      context: ./email_push_service
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: 'amqp://user:password@rabbitmq:5672'
      USER_SERVICE_URL: 'http://user-service:3000'
      TEMPLATE_SERVICE_URL: 'http://template-service:3000'
      SENDGRID_API_KEY: 'your_key_here'
    depends_on:
      - rabbitmq
      - user-service
      - template-service

volumes:
  rabbitmq_data:
  redis_data:
  api_db_data:
  user_db_data:
  template_db_data: