services:
  # Laravel PHP app
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api-gateway:/var/www/html
    depends_on:
      - rabbitmq
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:+vh95MvByNqLQTX9sNfWA5c37L4AHhtC2aEJC+aUnKs=
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - notification-network

  # Nginx for Laravel
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api-gateway:/var/www/html
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
    networks:
      - notification-network

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    networks:
      - notification-network

  #Postgres service
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: api_gateway
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - notification-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - notification-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    restart: unless-stopped
    working_dir: /app
    ports:
      - "4001:3001" # HOST:CONTAINER
    networks:
      - notification-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_NAME: user_service_db
      JWT_SECRET: 985f170205472e5a7f4f0b6e30c67d0b0abb274a4e8f394be805872b8c6e6a19
      JWT_EXPIRATION: 7d
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      PORT: 3001
      NODE_ENV: development

  email_push_service:
    build:
      context: ./email_push_service
    container_name: email_push_service
    restart: unless-stopped
    working_dir: /app
    ports:
      - "4002:3000" # HOST:CONTAINER
    networks:
      - notification-network
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EMAIL_QUEUE: email_queue
      PUSH_QUEUE: push_queue
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: taiwosamuel8364@gmail.com
      SMTP_PASS: zuunqtxozivvqfhm
      PORT: 3000
      NODE_ENV: development

    
  
  # template-service:
  #   build:
  #     context: ./template-service
  #   container_name: template-service
  #   restart: unless-stopped
  #   working_dir: /app
  #   ports:
  #     - "4002:3000" # HOST:CONTAINER
  #   networks:
  #     - notification-network
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: user
  #     DB_PASSWORD: pass
  #     DB_NAME: template_service
  #     PORT: 3000
  #     NODE_ENV: development

networks:
  notification-network:
    driver: bridge
